[[coordgenlibs]]
arch = "x86_64"
git-tree-sha1 = "593823fa386ca4deea0b2fc62d8d43b2ba93b8d6"
os = "macos"
os_version = "14.0.0"

    [[coordgenlibs.download]]
    sha256 = "2754f5dff3ee2ee9775a34b56a23010de29d93d00b6fe932e244e6fd97f69806"
    url = "https://github.com/mojaie/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.1+0/coordgenlibs.v3.0.1.x86_64-apple-darwin14.tar.gz"
[[coordgenlibs]]
arch = "x86_64"
git-tree-sha1 = "e23ac58f43a120b37ecccb7019c3cacffd264ba9"
os = "macos"

    [[coordgenlibs.download]]
    sha256 = "d219b13834bb03d05239ded8221ee331380fd6a0b9b36010d306732422b6f167"
    url = "https://github.com/mojaie/coordgenlibs_jll.jl/releases/download/coordgenlibs-v3.0.2+0/coordgenlibs.v3.0.2.x86_64-apple-darwin.tar.gz"
